// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBackPain.Data;

namespace MyBackPain.Migrations
{
    [DbContext(typeof(MyBackPainContext))]
    partial class MyBackPainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyBackPain.Models.BackPain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<string>("DidITakeIbuprofen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoIHaveBackPain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoIShakeMyFistsAtTheSky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsItMyFault")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BackPain");
                });
#pragma warning restore 612, 618
        }
    }
}
